name: Matrix Configuration Demo

on:
  push:
  workflow_dispatch:

jobs:
  matrix-deploy:
    runs-on: ${{ matrix.os }}
    
    strategy:
      # 1. Bir job hata aldığında diğer paralel işlerin iptal edilmesini engeller
      fail-fast: false
      
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [hello-world, alpine]
        
        # 2. Windows üzerinde Alpine imajının çalıştırılmasını matristen çıkarır
        exclude:
          - os: windows-latest
            images: alpine

    steps:
      - name: Docker Imajini Calistir
        run: docker run ${{ matrix.images }}