name: Exploring Secrets and Variables

on: push

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: nginx-app

jobs:
  docker_job:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        env:
          # Repository Secret çağrımı ($ controls masking)
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD1 }}
          # Repository Variable çağrımı
          DOCKER_USER: ${{ vars.DOCKER_USERNAME1 }}
        run: |
          echo "Logging in as $DOCKER_USER..."
          # $DOCKER_PASSWORD loglarda otomatik olarak *** şeklinde görünür
          echo "Password used: $DOCKER_PASSWORD"

      - name: Publish Docker Image
        run: |
          # Doğrudan vars context'i ile çağırma
          echo "Pushing image for user: ${{ vars.DOCKER_USERNAME1 }}"